export const LOGIN_API_CALL_START = "LOGIN_API_CALL_START";
export const LOGIN_API_CALL_SUCCESS = "LOGIN_API_CALL_SUCCESS";
export const LOGIN_API_CALL_FAILURE = "LOGIN_API_CALL_FAILURE";
export const REMOVE_AUTH_TOKEN = "REMOVE_AUTH_TOKEN";

export const REGISTER_API_CALL_START = "REGISTER_API_CALL_START";
export const REGISTER_API_CALL_SUCCESS = "REGISTER_API_CALL_SUCCESS";
export const REGISTER_API_CALL_FAILURE = "REGISTER_API_CALL_FAILURE";

export const IS_TOKEN_REGISTERED = "IS_TOKEN_REGISTERED";

export const IS_MENU_OPEN = "IS_MENU_OPEN";

export const LOGOUT_API_CALL_START = "LOGOUT_API_CALL_START";
export const LOGOUT_API_CALL_SUCCESS = "LOGOUT_API_CALL_SUCCESS";
export const LOGOUT_API_CALL_FAILURE = "LOGOUT_API_CALL_FAILURE";
export const LOGOUT_INITIAL_STATE = "LOGOUT_INITIAL_STATE";

export const DASHBOARD_API_CALL_START = "DASHBOARD_API_CALL_START";
export const DASHBOARD_API_CALL_SUCCESS = "DASHBOARD_API_CALL_SUCCESS";
export const DASHBOARD_API_CALL_FAILURE = "DASHBOARD_API_CALL_FAILURE";

export const GET_DASHBOARD_API_CALL_START = "GET_DASHBOARD_API_CALL_START";
export const GET_DASHBOARD_API_CALL_SUCCESS = "GET_DASHBOARD_API_CALL_SUCCESS";
export const GET_DASHBOARD_API_CALL_FAILURE = "GET_DASHBOARD_API_CALL_FAILURE";

export const GET_USER_DETAILS_START = "GET_USER_DETAILS_START";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const GET_TRANSACTION_ACTION_START = "GET_TRANSACTION_ACTION_START";
export const GET_TRANSACTION_ACTION_SUCCESS = "GET_TRANSACTION_ACTION_SUCCESS";
export const GET_TRANSACTION_ACTION_FAILURE = "GET_TRANSACTION_ACTION_FAILURE";

export const SET_TRANSACTION_ACTION_START = "SET_TRANSACTION_ACTION_START";
export const SET_TRANSACTION_ACTION_SUCCESS = "SET_TRANSACTION_ACTION_SUCCESS";
export const SET_TRANSACTION_ACTION_FAILURE = "SET_TRANSACTION_ACTION_FAILURE";

export const SET_TRANSACTION_COLUMN_ORDER = "SET_TRANSACTION_COLUMN_ORDER";
export const SET_TRANSACTION_ROW_SELECTION = "SET_TRANSACTION_ROW_SELECTION";
export const SET_TRANSACTION_PAGE = "SET_TRANSACTION_PAGE";
export const SET_TRANSACTION_ROWS_PER_PAGE = "SET_TRANSACTION_ROWS_PER_PAGE";

export const SET_TRANSACTION_TABLE_SELECT_ALL = "SET_TRANSACTION_TABLE_SELECT_ALL";
