export const LOGIN_API_CALL_START = "LOGIN_API_CALL_START";
export const LOGIN_API_CALL_SUCCESS = "LOGIN_API_CALL_SUCCESS";
export const LOGIN_API_CALL_FAILURE = "LOGIN_API_CALL_FAILURE";

export const REGISTER_API_CALL_START = "REGISTER_API_CALL_START";
export const REGISTER_API_CALL_SUCCESS = "REGISTER_API_CALL_SUCCESS";
export const REGISTER_API_CALL_FAILURE = "REGISTER_API_CALL_FAILURE";

export const IS_TOKEN_REGISTERED = "IS_TOKEN_REGISTERED";

export const IS_MENU_OPEN = "IS_MENU_OPEN";
